# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build Api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' 
      - name: Restore dependencies
        run: dotnet restore WładcyKostek.sln
      - name: Build the solution
        run: dotnet build WładcyKostek.sln --configuration Release --no-restore
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: dist
          path: bin/Release/net9.0/publish
  deploy:
    name: Deploy Apps
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.1.7
        with:
          name: dist
          path: .
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 20.82.145.167
          port: 21
          local-dir: api/
          username: ${{ secrets.ftp_acc }}
          password: ${{ secrets.ftp_password }}
