# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
on:
  workflow_dispatch:
      inputs:
        logLevel:
          description: 'Log level'
          required: false
          default: 'warning'
  push:
    branches:
    - master
jobs:
  build:
    name: Build Api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          
      - name: Clean dependencies
        run: dotnet clean WladcyKostek.sln     
        
      - name: Restore dependencies
        run: dotnet restore WladcyKostek.sln

      - name: Build the solution
        run: dotnet build WladcyKostek.sln --configuration Release --no-restore
        
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: bin
          path: /home/runner/work/wladcy-kostek-api/wladcy-kostek-api/WladcyKostek.Core/bin/Release/net9.0/
  deploy:
    name: Deploy Apps
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.1.7
        with:
          name: bin
          path: .
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 20.82.145.167
          port: 21
          server-dir: /api/
          username: ${{ secrets.ftp_acc }}
          password: ${{ secrets.ftp_password }}
